filetype plugin indent on

syntax on

colorscheme nord

set background=dark
set backspace=indent,eol,start
set belloff=all
set nocompatible
set completeopt=menuone,preview
set fillchars=
set hidden
set history=50
set nohlsearch
set incsearch
set listchars="eol:$,tab:»\ ,trail:·"
set number
set relativenumber
set splitbelow
set splitright
set wildmenu
set laststatus=2
set encoding=utf-8
set nowrap

set path=.,**

let $RC="$HOME/.vim/vimrc"
let $RTP=split(&runtimepath, ',')[0]

let g:lightline = {
			\ 'colorscheme': 'nord',
			\ }

nnoremap <Space> <Nop>
let mapleader=" "
