if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
	export XDG_CONFIG_HOME=$HOME/.config
	export XDG_SESSION_TYPE=wayland
	export XDG_CURRENT_DESKTOP=sway
	export MOZ_ENABLE_WAYLAND=1

	export GTK_IM_MODULE=fcitx
	export QT_IM_MODULE=fcitx
	export XMODIFIERS=@im=fcitx

	export SHLVL=0
	exec sway
fi
